// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdcZ8jItf2FPOLU3poZ_popFzloAgV5g',
    appId: '1:460720345002:web:27cce72682c491706865d3',
    messagingSenderId: '460720345002',
    projectId: 'agri-sol',
    authDomain: 'agri-sol.firebaseapp.com',
    storageBucket: 'agri-sol.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhPHJ3hFa5ev6P7j8MsmXwy7KzAkTuSk',
    appId: '1:460720345002:android:474a3aa74bd883446865d3',
    messagingSenderId: '460720345002',
    projectId: 'agri-sol',
    storageBucket: 'agri-sol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXDCKekmjzVs5_6EsJwPQ_-45zd-hZZwM',
    appId: '1:460720345002:ios:556b41107679531f6865d3',
    messagingSenderId: '460720345002',
    projectId: 'agri-sol',
    storageBucket: 'agri-sol.firebasestorage.app',
    iosBundleId: 'com.example.agrisol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcdcZ8jItf2FPOLU3poZ_popFzloAgV5g',
    appId: '1:460720345002:web:81fe16f7867eeb266865d3',
    messagingSenderId: '460720345002',
    projectId: 'agri-sol',
    authDomain: 'agri-sol.firebaseapp.com',
    storageBucket: 'agri-sol.firebasestorage.app',
  );
}
